# Generated by Django 2.0.7 on 2018-07-28 03:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='文章详情')),
            ],
        ),
        migrations.AlterField(
            model_name='fillblank',
            name='fbContent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='saContent',
            field=models.CharField(max_length=200),
        ),
    ]
