# Generated by Django 2.1.1 on 2018-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20180728_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleDetail',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer1',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer10',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer2',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer3',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer4',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer5',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer6',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer7',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer8',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='fbAnswer9',
        ),
        migrations.AddField(
            model_name='fillblank',
            name='fbAnswer',
            field=models.CharField(max_length=100, null=True, verbose_name='填空答案'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admId',
            field=models.CharField(max_length=20, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admName',
            field=models.CharField(max_length=20, verbose_name='登录名'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admPassword',
            field=models.CharField(max_length=30, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='fillblank',
            name='fbContent',
            field=models.CharField(max_length=200, verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='fillblank',
            name='fbCourse',
            field=models.CharField(max_length=20, verbose_name='科目类别'),
        ),
        migrations.AlterField(
            model_name='fillblank',
            name='fbGrade',
            field=models.CharField(max_length=5, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='saAnswer',
            field=models.TextField(max_length=500, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='saContent',
            field=models.CharField(max_length=200, verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='saCourse',
            field=models.CharField(max_length=20, verbose_name='科目类别'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='saGrade',
            field=models.CharField(max_length=5, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuId',
            field=models.CharField(max_length=20, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuName',
            field=models.CharField(max_length=20, verbose_name='登录名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuPassword',
            field=models.CharField(max_length=30, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaId',
            field=models.CharField(max_length=20, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaName',
            field=models.CharField(max_length=20, verbose_name='登录名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaPassword',
            field=models.CharField(max_length=30, verbose_name='登录密码'),
        ),
    ]
