# Generated by Django 2.1.1 on 2018-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_fillblank_fbscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20, verbose_name='词语')),
                ('type', models.CharField(max_length=15, verbose_name='词性')),
                ('sememes', models.CharField(max_length=200, verbose_name='义原')),
            ],
        ),
    ]
