# Generated by Django 2.1.1 on 2018-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_glossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fillBlankId', models.IntegerField()),
                ('answer', models.CharField(max_length=300, verbose_name='学生答案')),
            ],
        ),
        migrations.AlterField(
            model_name='fillblank',
            name='fbAnswer',
            field=models.CharField(max_length=300, null=True, verbose_name='填空答案'),
        ),
    ]
