# Generated by Django 2.1.1 on 2018-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_studentanswer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='alpha',
            field=models.FloatField(default=1.6, verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='beta1',
            field=models.FloatField(default=0.5, verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='beta2',
            field=models.FloatField(default=0.2, verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='beta3',
            field=models.FloatField(default=0.17, verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='beta4',
            field=models.FloatField(default=0.13, verbose_name='参数'),
        ),
    ]
